### ISSUE TITLE
Ability to change key bindings for addon

### ISSUE THREAD

**Issue by xendren** [syndenbock/MinimapButtonButton#12]
Unfortunately, I use a mouse that does not have a middle button, so I can't seem to find a way to move the button out of the center of my screen.  If the key bindings were in the interface for addons, I could change it to some other key binding or mouse button.

**Comment by syndenbock** [comment]
There is no proper way to link a normal keybinding to moving the button, but I will add an additional way of moving the button holding alt + dragging with left click.

**Comment by syndenbock** [comment]
The ability to move the button using any mouse button while holding the ALT key was added in this [commit](https://github.com/syndenbock/MinimapButtonButton/commit/8ae9d5ffc330294e4986d4d8409be133afd4ddbf) and released in [version 1.6.5](https://github.com/syndenbock/MinimapButtonButton/releases/tag/1.6.5).

**Comment by xendren** [comment]
Perfect.  Works great! I really appreciate the quick turn around.
