### ISSUE TITLE
Button stuck in center of screen and is unresponsive to mouse input or changes in mbb settings

### ISSUE THREAD

**Issue by jakedemian** [syndenbock/MinimapButtonButton#14]
Playing on 9.2.5.44325.

Clicking the button does nothing, it's locked in place.  Alt+click+drag not working, middle mouse button not working.

Still able to run commands, eg `/mbb set scale 2` and the interface says `MinimapButtonButtom setting scale was set to 2`, but the button doesn't actually change.

I cannot open the button menu, either. 

It seems like it's just frozen.

**Comment by syndenbock** [comment]
That sounds like an error is occuring.
Could you please enable error messages by typing "/console scriptErrors 1" in the chat and /reload afterwards?
If an error message pops up please post it here.
You can disable error messages again by typing "/console scriptErrors 0" in the chat.

**Comment by syndenbock** [comment]
Closing this due to missing response.
