### ISSUE TITLE
Including ExpansionLandingPageMinimapButton

### ISSUE THREAD

**Issue by Mcdrowd** [syndenbock/MinimapButtonButton#18]
Hello,

including the frame = ExpansionLandingPageMinimapButton caused the symbol to be displayed over another symbol and is very small.

Is it possible that this symbol behaves the same way as other minimap symbols and also takes over to the scaling? 

regards

**Comment by Mcdrowd** [comment]
I found a solution for the overlapping with:

/mbb set buttonsPerRow 3

Any Idea for the size/scale?

**Comment by syndenbock** [comment]
Are you using ElvUI?

**Comment by Mcdrowd** [comment]
Yes - I am Using ElvUI

With that in mind, I disabled ElvUI's minimap once, since I use Sexymap anyway due to a better scaling option.

Now ExpansionLandingPageMinimapButton is also displayed in the MBB and I have also included the GameTImeFrame.

Thank ypu for the hint.

**Comment by syndenbock** [comment]
The issue is because ElvUI tells the button to ignore its parents scale, causing the strange size and position.
I added code to tell the buttons to not ignore the scale anymore which fixed the issue (at least in the case of ElvUI)
