### ISSUE TITLE
Questie Shows outside of MBB until I click MBB

### ISSUE THREAD

**Issue by OnceWasPerfect** [syndenbock/MinimapButtonButton#20]
Not sure if its  MBB or Questie (both updated around the same time I noticed it) but now Questie always shows outside of MBB when I first log in to all my toons.  If I open MBB Questie instantly goes inside of it and then works for the rest of the session.  This happens at every log in. 

Edit:  this is WoLTK classic, and no errors in bugsack

**Comment by syndenbock** [comment]
This is due to Questie not creating its button right away but an indefinitive amount of time after logging in, which also seems to change with every update of Questie.
MBB will now scan buttons again one second after logging in as a workaround.
