### ISSUE TITLE
Request to toggle "you can dragon the button" tooltip.

### ISSUE THREAD

**Issue by alliepet** [syndenbock/MinimapButtonButton#22]
Hello this is just a request. I would love to be able to turn on or off the tooltip that says "You can drag the button by..." It sort of overtakes my whole map area and I hover over the map area a lot. Thanks for your work!!

**Comment by syndenbock** [comment]
Currently, the tooltip gets created after logging in if the button has not been moved before. So after you moved the button and then reload or relog, the tooltip should no longer be created. 
I will update the behaviour to remove the tooltip immediately after it was moved for the first time.

**Comment by syndenbock** [comment]
This was implemented in verson 1.10.1
