### ISSUE TITLE
auto close

### ISSUE THREAD

**Issue by CasualSpec** [syndenbock/MinimapButtonButton#27]
it does not auto close after a certain amount of time passes. just stays open. nor does it close when i hit Esc.

**Comment by syndenbock** [comment]
Have you set an auto-close time by using the "/mbb set autohide x" command? You need to set that for the button to close automatically. Also, the button is not supposed to close by pressing ESC.

**Comment by syndenbock** [comment]
@CasualSpec I'll close this issue for now because I haven't heard from you for a year. Feel free to reopen the issue if you need any further help!
