### ISSUE TITLE
Mouseover

### ISSUE THREAD

**Issue by nacedos** [syndenbock/MinimapButtonButton#28]
I've been fiddling with hidecompartment setting, but returns unknown setting for classic wow somehow?
![Untitled](https://github.com/syndenbock/MinimapButtonButton/assets/25367506/922fad62-b19b-4356-a2cb-d4d648738afb)

What I'm trying to achieve is a compartment on hide until you mouse over it effect for the button (not to confuse with #11) to not clutter more my UI, is there a way to replicate that? If there isn't I think it would be a great enhancement addition.

**Comment by syndenbock** [comment]
The "hidecompartment" setting is for hiding the addon compartment box that has been added to the retail default UI and therefore is not available in classic. And to be honest I didn't understand what you wanted to do.

**Comment by syndenbock** [comment]
Could you explain the actual functonality you wanted? Maybe I can implement it.
