### ISSUE TITLE
Newest update 20/4/2024

### ISSUE THREAD

**Issue by Vazygos** [syndenbock/MinimapButtonButton#31]
Since the newest update the addon stopped working. When I hover over the button, the window opens but no buttons are shown.

**Comment by syndenbock** [comment]
This sounds like a bad interaction with another addon that hides buttons until they are hovered over (most of the times Sexymap and LeatrixPlus). I will revert the latest change that tried to prevent such behaviour though.

**Comment by Vazygos** [comment]
> This sounds like a bad interaction with another addon that hides buttons until they are hovered over (most of the times Sexymap and LeatrixPlus). I will revert the latest change that tried to prevent such behaviour though.

this fixed it. thanks :)
