### ISSUE TITLE
Addon Not Loading CATA Classic

### ISSUE THREAD

**Issue by Aenimma** [syndenbock/MinimapButtonButton#32]
Hello, with the new patch and CATA Classic this addon is not loading anymore. I am not getting any errors all of the addon icons are around the minimap once more.

**Comment by syndenbock** [comment]
Can you try disabling all other addons that fiddle with the minimap?
I am online in Cataclysm Classic and it collects the Questie button just fine.

**Comment by Aenimma** [comment]
It is working now, 

I am getting this error which I am not sure if it's a postal error or a Minimap Button Error?

Date: 2024-05-02 15:04:20
ID: 10
Error occured in: Global
Count: 1
Message: Interface/AddOns/Postal/Postal.lua line 221:
   attempt to index global 'MiniMapMailFrameMixin' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Postal/Postal.lua"]:221: MAIL_CLOSED()
   [string "@Interface/AddOns/Postal/Postal.lua"]:110: ?()
   [string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109:
      ...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109
   [string "=[C]"]: ?
   [string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19:
      ...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15
   [string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: Fire()
   [string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120:
      .../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119
   [string "=[C]"]: CloseMail()
   [string "*MailFrame.xml:847_OnHide"]:1:
      [string "*MailFrame.xml:847_OnHide"]:1
   [string "=[C]"]: Hide()
   [string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:590: SetUIPanel()
   [string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:670: HideUIPanel()
   [string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:323:
      ...PanelManager/Classic/UIParentPanelManager_Shared.lua:315
   [string "=[C]"]: SetAttribute()
   [string "@Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager_Shared.lua"]:1115: HideUIPanel()
   [string "@Interface/AddOns/Blizzard_SharedXML/Classic/SharedUIPanelTemplates.lua"]:193:
      ...lizzard_SharedXML/Classic/SharedUIPanelTemplates.lua:184
Locals:
(*temporary) = <function> defined =[C]:-1

**Comment by syndenbock** [comment]
This is an error in Postal as can be seen in the first "Message" line where it says 
> Message: Interface/AddOns/Postal/Postal.lua line 221:

There is a comment with a fix on the Postal curseforge site too: https://www.curseforge.com/wow/addons/postal/comments

So I'll go ahead and close this issue.
