### ISSUE TITLE
Recent Update causing game to force disconnect me to login screen

### ISSUE THREAD

**Issue by chucacabrawow** [syndenbock/MinimapButtonButton#37]
Hello,

If i run this addon with Wowhead looter I get force disconnected to login screen, this only started happening after the recent update.

**Comment by chucacabrawow** [comment]
I've tried all my other addons, this only happens if I use MBB along with Wowhead looter. I tried disabling the minmap button for Wowhead Looter under it's settings but it didn't make a difference. For now I will disable Wowhead Looter.

**Comment by syndenbock** [comment]
Can you try installing an older version of MinimapButtonButton and see if the issue still happens? Cause I honestly have no idea why that would happen - especially not after the recent updates I made.

**Comment by chucacabrawow** [comment]
Sure thing. So I am running the MBB version 1.19.1 from yesterday and it seems to be working fine.

**Comment by chucacabrawow** [comment]
Yea 1.19.1 seems to be working fine then i switch back to 1.19.2 and am getting the issue again.

**Comment by chucacabrawow** [comment]
Well. it just crashed under the 1.19.1 version I'm not really sure whats going on. Let me know if you want me to try anything else.

**Comment by chucacabrawow** [comment]
My bad dude. I thought this was a MBB issue this is a Wowhead looter issue. I'll get in touch with them, the game only forces me back to login with that one enabled.

**Comment by syndenbock** [comment]
I'm kinda glad the issue wasn't with MBB cause I'd have no idea where it could come from. I hope they'll be able to resolve the issue quickly!
