### ISSUE TITLE
1.19.3 Breaks in WoW Classic SoD

### ISSUE THREAD

**Issue by sngreg** [syndenbock/MinimapButtonButton#38]
Had to revert back to 1.19.2 to show the button. When i updated to 1.19.3 the icon doesn't show up and all minimap icons show up as default. (I dont have any more debugging notes at this time, just wanted to let y'all know)

**Comment by syndenbock** [comment]
That's odd, there was only a very minimal change from 1.19.2. And for me version 1.19.3 works just fine and picks up Questie and Bugsack. Could you try disabling all other addons temporarilyand see if the button shows up? (You can use this addon to easily save and restore the addons you have enabled currently: [AddonProfiles](https://www.curseforge.com/wow/addons/addonprofiles). Or maybe install [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber) and [BugSack](https://www.curseforge.com/wow/addons/bugsack) to see if an error occurs?

**Comment by sngreg** [comment]
@syndenbock  - Thank you for the quick response and helpful resources to help troubleshoot. In the process of documenting the breaking change and downloading the 1.19.3 version, I am unbale to reproduce the error. It was happening on both accounts this morning, but now unable to reproduce after upgrading. Maybe something glitched during the update on curseforge. 

Anyways I will keep an eye on it and if it happens again I will provide more details with the addons above. For now I will close out this issue. Thanks again!

**Comment by syndenbock** [comment]
No problem, I'm glad the issue somewhat resolved itself! I also assume it was an issue during the update as sometimes addon update clients have weird hiccups.

I hope the issue doesn't reappear because as I said, the change from 1.19.2 was very minimal so I have no clue what could cause it :D
