### ISSUE TITLE
Add Classiccodex minimap button

### ISSUE THREAD

**Issue by notDavid** [syndenbock/MinimapButtonButton#5]
Hi there,

please consider adding the minimap button of [classiccodex](https://www.curseforge.com/wow/addons/classiccodex) if you can :)

Thank you!

**Comment by notDavid** [comment]
PS. Not sure if this is relevant, but i'm using Wow Classic...

**Comment by notDavid** [comment]
Thanks! :)

**Comment by syndenbock** [comment]
You're welcome :)
