### ISSUE TITLE
Option to exlude certain buttons

### ISSUE THREAD

**Issue by Haatveit88** [syndenbock/MinimapButtonButton#7]
This look really nice and clean so far, but the one (and really, only) feature I'm missing is being able to blacklist / exclude certain minimap buttons from being collated. For example, I want my WIM chat addon button to behave like normal, and be ignored by MBB.

Not really sure what a clean way to do it would be, but it's an infrequent operation so having to type a slash command to list collated buttons and then another command to exclude one of them by an ID or name would be plenty good enough imo.

I've made a PR with a working solution, but, no hard feelings if you want to do it yourself or don't like my approach! 😊

**Comment by syndenbock** [comment]
I have added this feature based on your implementation of it. I changed the commands for ignoring/unignoring a bit:

- `/mbb list` Lists all collected and ignored buttons
- `/mbb ignore <button name>`  Adds the given button name to the ignore list
- `/mbb unignore <button name>`  Removes the given button name from the ignore list
- `/mmb unignoreall`  Clears the ignore list
